####################################
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/Misvie/config-server-repo/
          searchPaths: assetsservice,organizationservice,specialroutesservice,zuulservice,authenticationservice
          username: native-cloud-apps
          password: 0ffended
