spring:
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: assetGroup
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost

#        input:
#          destination: orgChangeTopic
#          content-type: application/json
#          group: assetGroup

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    rasoly.thoughtmechanix: DEBUG

